### ISSUE TITLE
FR: Allow jumping to the end of the episode even if the remaining time is less than defined jump

### ISSUE THREAD

**Issue by woj-tek** [dyerc/Doughnut#117]
Currently, if the remaining episode time is less than configured jump/skip time, it's not possible to jump to the end of the episode (and basically mark it as played, due to recent change to consider episode played when it reaches 100%, which is ok). 

It would be nice to be able to jump to the end of the episode even in the case where the jump would be smaller than defined skip time (i.e. we have skip time 30s but there is only 25s of the episode remaining).

**Comment by GetToSet** [comment]
Thanks for reporting this issue! I'll get this fixed it in the next release.
