### ISSUE TITLE
RAM usage rises steadily to ~50GB

### ISSUE THREAD

**Issue by DanielVolz** [dyerc/Doughnut#21]
While listening to podcasts with Doughnut I noticed that after some time I get a prompt from OSX to quit an application because there is no memory left for other apps.
The app that used up all the RAM was Doughnut with incredible ~50 GB. Most of it was in swap memory.

The screenshot below show the high RAM usage. 
While making this post it grew to ~20 GB.

<img width="703" alt="Screenshot 2019-11-22 at 15 52 14" src="https://user-images.githubusercontent.com/3275994/69436076-00762700-0d41-11ea-9a9c-43e4dfd2a77c.png">

**Comment by dyerc** [comment]
Thanks for posting this issue report @DanielVolz , I will investigate further. Please could you confirm which version of Doughnut you are on? 

How long do you think Doughnut had been running for when the RAM usage reached 12GB? I've been listening all morning today and my memory usage has stayed around 250MB so there must be a bug or edge-case being triggered somewhere to cause the memory leak.

**Comment by DanielVolz** [comment]
Thanks for the reply.
I'm using the most current 1.1.1 version. Doughnut was running about 15 min when it reached 12 GB the last time.

But strangely I can't reproduce the memory leak today.
Maybe it depends on the podcast I'm listening to? 
Right now it allocates about 950 MB.

I will try other podcasts and report back if it happens again.

<img width="1154" alt="Screenshot 2019-11-26 at 15 14 48" src="https://user-images.githubusercontent.com/3275994/69641057-c918ba80-105f-11ea-80ce-94be61defa68.png">


<img width="586" alt="Screenshot 2019-11-26 at 15 16 22" src="https://user-images.githubusercontent.com/3275994/69641156-f8c7c280-105f-11ea-94e2-9da7e54d2230.png">

**Comment by woj-tek** [comment]
I also have this problem though it doesn't go as high -- currently it reached 2,5G after listening podcasts for about 3h today (about 10 episodes of 15-20 minutes from one podcast):
<img width="877" alt="Screenshot 2022-01-11 at 14 11 40" src="https://user-images.githubusercontent.com/724413/148948557-ec08bc2a-228c-4140-89d3-017a6d3ad879.png">

After the restart it starts with about 250M but then it start to refresh feeds (I have quite a lot of them with lots of episodes) and it reaches 6G and then it decreases to 2,9G.

I think it's not related to playback itself but to the data retrieval (leak?) and storing all the information in the memory. My Doughnut database is ~30M.

**Comment by woj-tek** [comment]
With the 2.0.0-beta2 My memory usage seems to be rather stable at around 1,5G (which is good, though I think it could be somewhat optimised more maybe :-) )

**Comment by woj-tek** [comment]
With RC1 memory usage went down to ~150M! This is awesome!
