### ISSUE TITLE
Progress to the v2.0.0 version.

### ISSUE THREAD

**Issue by GetToSet** [dyerc/Doughnut#48]
## For the version 2.0

- [x] Upgrade to Xcode 13 & Swift 5 with minimum OS of 10.15.
- [x] Third party dependency updates & Apple Silicon build.
- [x] SwiftLint.
- [x] Modern appearance for the preference pane.
- [x] Fix top crashes.
- [x] Menu and shortcut refinements.
- [x] Batch operations to mark as played and favorite.
- [x] Modern appearance for main window.
- [x] Theme accent color.
- [x] Action menu on Dock icon.
- [x] Removal of SPMediaKeyTap and add support for Media Player API.
- [x] Collecting crash with PLCrashReporter.
- [x] Redesigned app icon.
- [x] Image related memory issues.
- [x] Asynchronously loading audio assets.
- [x] Properly respond to theme changes.

**Comment by dyerc** [comment]
Thanks @GetToSet , your work on updating Doughnut is much appreciated!

All of these items would be great improvements to Doughnut in the future. I'm still not keen on redesigning the app icon at present. You're welcome to play around with some ideas but I don't want to change it simply because Apple discourages round icons. I'm quite fond of the round hollow icon!

**Comment by woj-tek** [comment]
I agree with @dyerc regarding the icon - it looks good and it's easier to distinguish (and I dislike a lot Apples new fad)

**Comment by GetToSet** [comment]
I'm not that keen on iOS styled app icons on Mac. I agree with @dyerc that changing the icon is a serious decision.

Actually, I found that [MacUpdater](https://www.corecode.io/macupdater/) provides a preference option to allow users to select the icon style they like.
<img width="677" alt="Screen Shot 2022-01-27 at 13 49 19" src="https://user-images.githubusercontent.com/8158163/151300772-27ce049e-ee4a-47c8-8d7b-d134801a6b43.png">

<img width="230" alt="Screen Shot 2022-01-27 at 14 05 30" src="https://user-images.githubusercontent.com/8158163/151301371-54d351c7-8968-4a6f-9259-72ff5bcc0930.png">

This might be an alternative to directly changing the app icon.

**Comment by woj-tek** [comment]
Given that 2.0 is out maybe it would be a good idea to group task for future versions using [projects](https://github.com/dyerc/Doughnut/projects?type=new) instead of a checklist in issue?

**Comment by dyerc** [comment]
You read my mind @woj-tek! Was literally just looking through to see what issues I could close off now and thought just the same.

**Comment by woj-tek** [comment]
My comment was prompted by your merges :-D

**Comment by dyerc** [comment]
@GetToSet, I've made you an admin on a blank project I've made as a starting point. How would you like to structure it? My initial thinking was as a board with columns for 2.1, 2.2, 3.0 etc. An inbox column and perhaps "In Progress"? What do you think?

**Comment by GetToSet** [comment]
> @GetToSet, I've made you an admin on a blank project I've made as a starting point. How would you like to structure it? My initial thinking was as a board with columns for 2.1, 2.2, 3.0 etc. An inbox column and perhaps "In Progress"? What do you think?

Personally I prefer using tags instead tags for versions, and columns should be better used to indicate current status.

I'll take convert items in this list into separate issues so they can be attached to the project. I'll reorganize them with a new outline issue and close this one, perhaps tomorrow.

**Comment by GetToSet** [comment]
Closed with the v2.0.0 release.
