### ISSUE TITLE
Upon startup with default window size some buttons are hidden

### ISSUE THREAD

**Issue by woj-tek** [dyerc/Doughnut#62]
After recent UI changes (which are great btw!) some UI controls are hidden behind ellipsis until UI is resized/extended:
<img width="1054" alt="Captura de pantalla 2022-03-06 a las 14 24 19" src="https://user-images.githubusercontent.com/724413/156925172-3a147950-368e-4094-b7f2-e8614b1c18c4.png">
<img width="1091" alt="Captura de pantalla 2022-03-06 a las 14 24 30" src="https://user-images.githubusercontent.com/724413/156925181-c518c3f3-819a-4b22-b40f-5abe3abd4df6.png">

Resizing, even by a couple of pixels, restores the UI (and surprisingly, hides the name of the selected podcast):
<img width="1062" alt="Captura de pantalla 2022-03-06 a las 14 24 43" src="https://user-images.githubusercontent.com/724413/156925189-fcc4cbc1-af73-4144-9efb-171ec8fa284e.png">

**Comment by GetToSet** [comment]
Since toolbar buttons have been assigned with priorities, the last behavior should be correct.

It might be due to some dirty data related to the window size stored in the preference, and this should only happen once after the upgrade.

If you could reproduce the issue, please let me know the steps needed and your OS version.

**Comment by woj-tek** [comment]
I'm on "12.2.1 (21D62)". It happens every time I start the application. One possibility could be locale of my system (Spanish) but on the other hand Doughnut is in English so this shouldn't make any difference.

**Comment by GetToSet** [comment]
> I'm on "12.2.1 (21D62)". It happens every time I start the application. One possibility could be locale of my system (Spanish) but on the other hand Doughnut is in English so this shouldn't make any difference.

That seems wired, still having no clues about why this happens. Could you navigate to `~/Library/Preferences`, backup and remove `com.cdyer.doughnut.plist` to see if it still happens. This should fix the problem and you can attach a copy of this plist file so that I can further investigate this issue.

**Comment by woj-tek** [comment]
I removed the issue and the same problem happens. I thought that either `MASPreferences Frame Top Left`, `MASPreferences PrefGeneralViewController Frame` or `NSWindow Frame PodcastWindow` could be to blame but seems not. One more thing - I have a second external display (27", WQHD). Here's the file (converted to XML to make it more accessible instead of attaching binary).

```xml
$ cat ~/Library/Preferences/com.cdyer.doughnut.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>MASPreferences Frame Top Left</key>
	<string>{820, 418}</string>
	<key>MASPreferences PrefGeneralViewController Frame</key>
	<string>{{0, 0}, {620, 92}}</string>
	<key>MASPreferences Selected Identifier View</key>
	<string>PrefGeneralViewController</string>
	<key>NSSplitView Subview Frames Main</key>
	<array>
		<string>0.000000, 0.000000, 311.000000, 491.000000, NO, NO</string>
		<string>312.000000, 0.000000, 318.000000, 491.000000, NO, NO</string>
		<string>631.000000, 0.000000, 420.000000, 491.000000, NO, NO</string>
	</array>
	<key>NSWindow Frame PodcastWindow</key>
	<string>641 -810 527 359 396 -1117 1728 1079 </string>
	<key>SUEnableAutomaticChecks</key>
	<true/>
	<key>SUHasLaunchedBefore</key>
	<true/>
	<key>SULastCheckTime</key>
	<date>2022-03-06T10:25:38Z</date>
	<key>SUSendProfileInfo</key>
	<false/>
	<key>Volume</key>
	<real>1</real>
	<key>enableMediaKeys</key>
	<true/>
	<key>episodeSortDirection</key>
	<string>Ascending</string>
	<key>episodeSortParam</key>
	<string>Most Recent</string>
	<key>libraryPath</key>
	<string>~/Music/Doughnut</string>
	<key>podcastSortDirection</key>
	<string>Ascending</string>
	<key>podcastSortParam</key>
	<string>Unplayed</string>
	<key>replayAfterPause</key>
	<false/>
	<key>showDockBadge</key>
	<false/>
	<key>skipBackDuration</key>
	<integer>5</integer>
	<key>skipForwardDuration</key>
	<integer>15</integer>
</dict>
</plist>
```

**Comment by GetToSet** [comment]
Thanks for @woj-tek. Finally, I got this problem reproduced. It's about the state restoration mechanism that I'm not much familiar with. It's completely different from the previously mentioned autosave mechanism. You can reference [this thread](https://apple.stackexchange.com/questions/375746/how-to-read-and-manipulate-library-saved-application-state-com-apple-finder-sa) for detailed information.

There's a toggle in system preference to disable this behavior globally. With it toggled on, no window state will be preserved for Doughnut, resulting in this improper layout every time on launch.

<img width="667" alt="Screen Shot 2022-03-07 at 23 21 43" src="https://user-images.githubusercontent.com/8158163/157063103-634e32b8-67bb-4779-802c-b6ce82b38641.png">

I'll try to fix this layout issue.

**Comment by woj-tek** [comment]
OMG! Thank you! It works now (and even the window size/location is preserved). What a dumb option Apple has introduced...

(though, some sort of workaround/warning during startup could be added to notify the user?)

**Comment by GetToSet** [comment]
> (though, some sort of workaround/warning during startup could be added to notify the user?)

Applications can override this behavior by explicitly setting `NSQuitAlwaysKeepsWindows` defaults key. Some open-source application provides this setting in their preferences(e.g. CotEditor). iTerm2 warns user that state restoration is being disabled in system preferences, but not override this setting.
<img width="897" alt="2022-03-08 AM1 13 19" src="https://user-images.githubusercontent.com/8158163/157084633-ae3dee86-9e55-4b11-9df1-8ba9fb753a8b.png">

The use of `NSQuitAlwaysKeepsWindows` seems controversial, [NetNewsWire](https://github.com/Ranchero-Software/NetNewsWire/blob/27dd920cce355a976fa68ca7bf3f4e25b0095196/Mac/AppDefaults.swift#L341) removed this hack and with commit message of "needing more study".

**Comment by woj-tek** [comment]
I think that iTerm approach seems to be the cleanest one, though Doughtnut doesn't have settings for window management/restoration (so maybe just a warning at the bottom of the Preference window?)
