### ISSUE TITLE
Skip backwards/ahead doesn't resepect configuration

### ISSUE THREAD

**Issue by woj-tek** [dyerc/Doughnut#79]
## Steps to Reproduce:

1. Set non-standard values to skip back/ahead (in my case 5/15 seconds)
2. Try to skip back (with keyboard)

**Expected results:**
I should go back 5 seconds

**Actual results:**
I'm taken back 15 seconds (i.e. default value

## Additional Information:

- Doughnut Version: Version 2.0.0-beta.2 (1647976645)

**Comment by GetToSet** [comment]
Fixed on #74.

**Comment by woj-tek** [comment]
That was blazing fast! Thank you :-)
