### ISSUE TITLE
Add to Homebrew Cask

### ISSUE THREAD

**Issue by NightMachinary** [dyerc/Doughnut#9]

**Comment by CD1212** [comment]
I've just been reading through the submission guide for Homebrew Casks and [reasons casks can be rejected](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/rejected_casks.md) one of which is 

> The Cask is too obscure (for example, a self-submitted app from a GitHub repository that is not notable enough (under 50 stars)).

I wonder whether to give it a few months, when hopefully more issues with Doughnut will be fixed and it might be above 30 stars. What do you think?

**Comment by NightMachinary** [comment]
Ah, that's quite an unfortunate policy, I think. I suggest you try it
anyways, because there aren't many podcast players on macOS ... And it
really is much easier to just type a command to install sth; It should help
adoption. It also gives an aura of credibility, as `obscure apps` indeed
lack a cask😂🔫
Good luck!

**Comment by woj-tek** [comment]
It's also possible to create local tap for cask.

**Comment by woj-tek** [comment]
Hi,
I would like to bump this issue. I can't make a proper PR because homebrew casks require dedicated repository, in case of Doughnut it would be `dyerc/homebrew-Doughnut`. In said repository we would have to put `doughnut.rb` file under `Casks` directory (i.e.: `Casks/doughnut.rb`):

```ruby
cask 'doughnut' do
  version '1.1.1'
  sha256 'e50a64f6325bc88378f04848213ff745360d6a84a7533e7ad93b5abe53015ba9'

  url "https://github.com/dyerc/Doughnut/releases/download/v#{version}/Doughnut-#{version}.dmg"
  appcast 'https://github.com/dyerc/Doughnut/releases.atom'
  name ' Doughnut'
  desc 'Podcast client (podcatcher) for Mac'
  homepage 'https://github.com/dyerc/Doughnut'

  #depends_on macos: ">= :catalina"

  app "Doughnut.app"

  zap trash: [
    "~/Library/Preferences/com.cdyer.doughnut.plist",
    "~/Music/Doughnut",
  ]
end
```

I'm not sure about dependency and whether I got all data directories/files. I checked it locally and it works just fine (save for the FileVault requirement)

I created example repository: https://github.com/woj-tek/homebrew-doughnut (@dyerc if you agree I could transfer it to you)

**Comment by dyerc** [comment]
@woj-tek Thank you very much for putting this together. Would you be able to transfer the cask repository to me and I can have a good at testing/submitting it.

**Comment by woj-tek** [comment]
"Repository transfer to dyerc requested" :-)

**Comment by dyerc** [comment]
Now submitted 🎉 https://github.com/Homebrew/homebrew-cask/pull/117200

@woj-tek I had to create a new repository forked from Homebrew/homebrew-cask which just made it easier when following the submit a cask document. Your caskfile was very much the basis of everything though, thank you!

**Comment by woj-tek** [comment]
Ah, The difference is that the repo I created could be used as tap without having to submit it to main homebrew repo, i.e. you create any repository and then call `brew tap dyerc/Doughnut` and it just works. On the plus side is that you have complete control over what's there. The downside is that people have to add your tap. I hope it will get approved in the main repo though - better visibility 👍
